xamarin/ios-samples

- WatchKit/WatchKitCatalog/WatchkitExtension/Glance/GlanceController.cs
Fixed GlanceController Awake method as it was not finding the image Walkaway, it was throwing a NullException, preventing the app to start in the watch simulator.
Changed to the same value that is being used in the ImageDetailController.
> [WatchKitCatalog] Fixed GlanceController Awake method

- Location/Location/LocationManager.cs
New in iOS 9 and required to enable background location updates:
https://developer.apple.com/library/prerelease/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/index.html#//apple_ref/occ/instp/CLLocationManager/allowsBackgroundLocationUpdates
> iOS 9 background updates fix

- AppPrefs/AppDelegate.cs
- AppPrefs/AppPrefsViewController.cs
- AppPrefs/Settings.cs
RegisterDefaults should be called unconditionally before querying NSUserDefaults. Otherwise if you happen to set the first name in settings then none of the other defaults will work unless the user happened to set them all.
I have seen at least two people on the forums get confused by this issue (one example: https://forums.xamarin.com/discussion/58886/nsuserdefaults-standarduserdefaults-value-returns-null). The first time I thought it was their own misunderstanding, but the second one made me realize it was this example that was leading them down the wrong track. I think this pull request makes the proper usage of this API clearer.
> Fix use of RegisterDefaults.

- FileSystemSampleCode/FileSystem/Classes/Account.cs
- FileSystemSampleCode/FileSystem/FileSystem.csproj
As stated in bug [37242](https://bugzilla.xamarin.com/show_bug.cgi?id=37242) the sample does not work because the different
properties are read only. This happens when the linker is set to link
everything because the different getter methods are not used.
In this case, we want to keep those methods that are not used so that
the json library, which uses reflection, can find readable properties.
> [Fix] Do not use 'Link All' to ensure that reflection works.

- ZoomingPdfViewer/PdfScrollView.cs
- ZoomingPdfViewer/ZoomingPdfViewerViewController.cs
This PR contains fix for the ZoomingPdfViewer  sample, bug  https://bugzilla.xamarin.com/show_bug.cgi?id=37829
> [ZoomingPdfViewer] Fix for #37829

- SimpleBackgroundTransfer/SimpleBackgroundTransfer/Info.plist
- SimpleBackgroundTransfer/SimpleBackgroundTransfer/SimpleBackgroundTransferViewController.cs
The download was failing because the original image url no longer exists.
I updated the image url to a working url that also uses https to abide by iOS App Transport Security
> Updated SimpleBackgroundTransfer Image URL

- ios9/HomeKitCatalog/HomeKitCatalog/Info.plist
Fix bug #44068: [iOS10]Monotouch application "HomeKitCatalog" crash as soon as it launches on device
(https://bugzilla.xamarin.com/show_bug.cgi?id=44068)
> [HomeKitCatalog] Add missing privacy key

- ios9/SamplePhotoApp/SamplePhotoApp/Info.plist
Fix bug #44067: [iOS10]Monotouch application "SamplePhotoApp" crash as soon as it launch on device
(https://bugzilla.xamarin.com/show_bug.cgi?id=44067)
> [SamplePhotoApp] Add missing privacy key

- watchOS/WatchComplication/iOSApp.WatchAppExtension/iOSApp.WatchAppExtension.csproj
- watchOS/WatchLocalization/Localization.WatchAppExtension/Localization.WatchAppExtension.csproj
- watchOS/WatchPuzzle/WatchPuzzle.WatchKitAppExtension/WatchPuzzle.WatchKitAppExtension.csproj
- watchOS/WatchTables/WatchTables.OnWatchExtension/WatchTables.OnWatchExtension.csproj
Fixes error
```
Error MT2015: Invalid HttpMessageHandler `HttpClientHandler` for watchOS. The only valid value is NSUrlSessionHandler. (MT2015)
```
> Update WatchOS samples to use NSUrlSessionHandler instead of HttpClientHandler MT2015

- ManualCameraControls/ManualCameraControls/BracketedViewController.cs
I added a required validation in order to avoid multiple Capture Bracket Camera calls.
https://bugzilla.xamarin.com/show_bug.cgi?id=43779
> Fixed crash related to capture bracket view

- AVCaptureFrames/Info.plist
Fixed problem where sample was auto-closed by iOS 10 increased privacy protections
> [AVCaptureFrames] Added iOS 10-required privacy description to info.plist

- watchOS/WatchComplication/README.md
While using MacBook up/down arrows on keyboard don't work, have to use swipe up/down on Trackpad.
> Updated readme to include crown swipe from macbook

- intro-to-extensions/ContainerApp/Info.plist
- intro-to-extensions/DayCountExtension/Info.plist
- ios10/ElizaChat/ElizaChat/ElizaChat.csproj
- ios9/MetalPerformanceShadersHelloWorld/MetalPerformanceShadersHelloWorld/Info.plist
- ios9/MetalPerformanceShadersHelloWorld/MetalPerformanceShadersHelloWorld/MetalPerformanceShadersHelloWorld.csproj
Set code-signing to development/automatic in a sample app. Fixed deployment target of two sample apps to wokaround a build error if only 11.0 is targeted bug 58156.
> Set deployment target to 9.0 

- CustomTransitions/CustomTransitions/CustomTransitions.csproj
- ios11/ARKitPlacingObjects/PlacingObjects/PlacingObjects.csproj
- ios11/ARKitSample/ARKitSample/ARKitSample.csproj
- ios11/CoreML/MarsHabitatPricePredictor/MarsHabitatPricePredictor.csproj
- ios11/CoreMLImageRecognition/CoreMLImageRecognition/CoreMLImageRecognition.csproj
- ios11/CoreMLVision/CoreMLVision/CoreMLVision.csproj
- ios11/DragAndDropCustomView/CustomViewDragAndDrop/CustomViewDragAndDrop.csproj
- ios11/DragAndDropDragBoard/DragBoard/DragBoard.csproj
- ios11/MapKitSample/Tandm/Tandm.csproj
- ios11/NFCTagReader/NFCTagReader/NFCTagReader.csproj
- ios11/PDFAnnotationWidgetsAdvanced/PDFAnnotationWidgetsAdvanced/PDFAnnotationWidgetsAdvanced.csproj
- ios11/PDFDocumentWatermark/DocumentWatermark/DocumentWatermark.csproj
- ios11/VisionFaces/VisionFaces/VisionFaces.csproj
- ios11/VisionRectangles/VisionRects/VisionRects.csproj
- watchOS/WatchKitCatalog/WatchKit3Extension/WatchKit3Extension.csproj
1. A few iOS 11 samples targeted both armv7+arm64 which resulted in error "MTOUCH : error MT0116: Invalid architecture: i386. 32-bit architectures are not supported when deployment target is 11 or later."  Updated iOS 11 samples to target only 64 bit architecture. 
2. Updated samples to use Developer/Automatic keys and not external test keys.
> Xisamplearchfix

- ios11/MapKitSample/Tandm/Classes/BikeView.cs
- ios11/MapKitSample/Tandm/Classes/ClusterView.cs
- ios11/MapKitSample/Tandm/ViewController.cs
On iOS 11 an app using MapKit and the clustering crashes after a while as described on the following link : https://forums.developer.apple.com/thread/89427
This PR brings the workaround to the sample Tandm.
> iOS 11 MapKit with clustering crash workaround

- ios11/MusicKitSample/MusicKitSample/MusicKitSample.csproj
Update MusicKitSample to only 64 bit arch.
> Update architecture to point to arm64 and x86_64 for iOS11 sample

- ios10/AVCamManual/AVCamManual/AVCamManual/AVCamManualCameraViewController.cs
According to #198, the `PHAssetCreationRequest.CreationRequestForAsset ().AddResource` method can be used using an `NSData` or a file path parameter. The current implementation uses the `NSData` implementation using a file path, which is wrong.
> Should use filePath as NSUrl

- .gitignore
- InfColorPicker/InfColorPickerBinding/InfColorPickerBinding/InfColorPickerBinding.csproj
- added AllowUnsafeBlocks attribute to groups where it was absent - because of it XI test failed 
- added a new ".vs" folder to the `.gitignore` file
> [XI] added `AllowUnsafeBlocks` attribute and modify the .gitignore file

- Notifications/Application.cs
- Notifications/Entitlements.plist
- Notifications/Info.plist
- Notifications/Notifications.csproj
- added `Entitlements.plist`
- cleared `Application.cs`
- updated `CFBundleIdentifier`
After launch the app showed an error message that it couldn't register push notifications. There were two reasons:
- Entitlements.plist wasn't exist;
- there were wrong "BundleIdentifier" and developer certificate;
Also I updated the `CFBundleIdentifier` key because we couldn't register the application with `com.*.notifications` key because of Apple limitation (as I understood).
> [XI] fixed the "Notification" sample

- Sound/Sound/SoundViewController.cs
If permissions hasn't been asked for yet then the callback from this the first time
```C#
session.RequestRecordPermission(delegate (bool granted)
{
```
comes back on a background thread causing this code
```C#
LengthOfRecordingLabel.Text = string.Empty;
RecordingStatusLabel.Text = "Recording";
StartRecordingButton.Enabled = false;
StopRecordingButton.Enabled = true;
PlayRecordedSoundButton.Enabled = false; 
```
to throw an exception
> set ui elements on the uithread after asking for permission

- ios11/DragAndDropDragBoard/DragBoard/Info.plist
- ios11/DragAndDropMastering/DragSource/Info.plist
- ios11/DragAndDropMastering/DropDestination/Info.plist
Fixed wrong device family for Drag&Drop samples. This feature is only supported on the iPad.
> [XI] fixed wrong device family

- Chat/Chat/ChatViewController.cs
If using the Cmd+K shortcut on the simulator to show the keyboard, it will called twice KeyboardWillShowHandler. So I do a counter.
And change keyboard to Chinese keyboard still has some problem.
Also I found if without View.LayoutIfNeeded (no animation), it will work fine.
> #237 Fix layout problems (regarding Keyboard) in Chat sample

- ios8/DocPicker/DocPicker/Entitlements.plist
- ios8/DocPicker/DocPicker/Info.plist
- auto-added missed properties to `Info.plist`
- improved `Entitlements.plist` files by adding `$(CFBundleIdentifier)`. It will help us be more flexible with bundle identifier and profiles
> [XI] improved iCloud container; "DockPicker" sample

- LifecycleDemo/LifecycleDemo/LifecycleDemo.csproj
After the latest Craig's [changes](https://github.com/xamarin/ios-samples/commit/3680b0d2a8c42deb23c793a4d63e62264b8572c4) the samples fails to build in Release mode because of bad arch:
```
MTOUCH : error MT0116: Invalid architecture: ARMv7. 32-bit architectures are not supported when deployment target is 11 or later. 
```
> [LifecycleDemo] fixed release config

- ios11/SamplePhotoApp/Shared/AnimatedImage.cs
Passing null to CopyProperties throws this exception
```
{System.ArgumentNullException: Value cannot be null. Parameter name: options   at ImageIO.CGImageSource.CopyProperties (ImageIO.CGImageOptions options) [0x00003] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.12.0.4/src/Xamarin.iOS/ImageIO/CGImageSour…}
```
So I changed it to just pass a default instantiated
```
new CGImageOptions()
```
And now it plays animations without throwing an exception
> fix ArgumentNullException when passing null to CopyProperties

- Profiling/MemoryDemo/MemoryDemo/MemoryDemo.csproj
Make sure the same output path isn't used with multiple configurations by
using the correct configuration name in the output path.
> [MemoryDemo] Make sure the same output path isn't used with multiple configurations.

- ios13/RefreshingAndMaintainingYourAppUsingBackgroundTasks/ColorFeed/Info.plist
- https://github.com/xamarin/ios-samples/issues/392
> Fix ColorFeed sample by adding required Info.plist keys

- FileSystemSampleCode/WorkingWithTheFileSystem.sln
The FileSystem2.csproj project does not exist, its entry has been
removed from WorkingWithTheFileSystem.sln.
> Remove invalid project from FileSystemSampleCode

- UICatalog/UICatalog/Controllers/Toolbars/CustomToolbarViewController.cs
a new API with a similar signature (wrt null) was added in XI 14
> [UICatalog] Fix ambiguous call in sample

- ios12/SoupChef/OrderSoupIntentStaticLib/Makefile
- ios12/SoupChef/OrderSoupIntentStaticLib/OrderSoupIntentStaticLib.xcodeproj/project.pbxproj
Xcode 12.2
- adds `arm64` to the simulator architectures
- removes `i386` from the simulator architectures
`lipo` cannot create a _classic_ fat archive with `arm64` simulator and
`arm64` device slices - since they are the same architecture.
This requires `.xcframework` support which is not yet supported by XI
and XM.
However we can tweak the build to do:
- x86_64 only for simulator, which is the only support arch for XI today
- arm64 for devices
and that makes `lipo` happy and we can continue to have this sample under
test automation.
Note: the original `.a` names were incorrect as they did not match the
architectures that were present in the files. I changed them to mention
the platform.
> [SoupChef] Fix build with Xcode 12.2

- SimpleBackgroundTransfer/SimpleBackgroundTransfer/SimpleBackgroundTransferViewController.cs
- Fixes https://github.com/xamarin/ios-samples/issues/406
- Optional protocol methods must export if you use IFoo instead of Foo base class
> Correct SimpleBackgroundTransfer sample to export optional protocol selectors

- dotnet/ios/ios12/BreakfastFinder/BreakfastFinder/BreakfastFinder.csproj
- dotnet/ios/ios12/BreakfastFinder/BreakfastFinder/Info.plist
- dotnet/ios/ios12/BreakfastFinder/BreakfastFinder/ViewController.cs
- dotnet/ios/ios12/VisionObjectTrack/VisionObjectTrack/AssetsViewController.cs
I was able to build the 3 samples here (plus a PR I updated) against the latest macios and have zero availability warnings after these fixes. 
They come in two flavors:
- Compile errors caused by last minute API breaks
- Bumping the minimum version because the availability warnings were legit.
> API fixes in NET6 samples
