xamarin/ios-samples

WatchKit/WatchTables/WatchTablesExtension/InterfaceController.cs
The if statement is not needed. Not sure if intent was meant to show
something else?
=> Redundant if?

iOS7-ui-updates/AppDelegate.cs, iOS7-ui-updates/ImageViewController.cs, iOS7-ui-updates/Main.cs
This pull request contains improved fix for [37455](https://bugzilla.xamarin.com/show_bug.cgi?id=37455) and sample code refactoring.
=> ImageView sample refactoring

LowLevelGLPaint/PaintingView.cs
This PR contains fix for https://bugzilla.xamarin.com/show_bug.cgi?id=37416
=> LowLevelGLPaint fix for Bug37416

ios8/VideoTimeLine/VideoTimeLine/Info.plist, ios8/VideoTimeLine/VideoTimeLine/VideoTimeLine.csproj, ios8/VideoTimeLine/VideoTimeLine/ViewController.cs
This PR contains the fix for sample Video Time Line https://bugzilla.xamarin.com/show_bug.cgi?id=41355
=> [VideoTimeLine] Fix for bug #41355

ios8/MotionActivityDemo/MotionActivityDemo/Info.plist
Added key required for ios10 compatibility.
=> Added missing key to MotionActivityDemo

AUSoundTriggeredPlayingSoundMemoryBased/Info.plist
Added missing required (ios 10) privacy key on .plist file.
=> Added missing key

Protocols_Delegates_Events/Xib Solution/AppDelegate.cs, Protocols_Delegates_Events/Xib Solution/Info.plist, Protocols_Delegates_Events/Xib Solution/Main.cs, Protocols_Delegates_Events/Xib Solution/Protocols_Delegates_Events.csproj, Protocols_Delegates_Events/Xib Solution/Protocols_Delegates_EventsViewController.cs, Protocols_Delegates_Events/Xib Solution/Protocols_Delegates_EventsViewController.designer.cs, Protocols_Delegates_Events/Xib Solution/SampleMapAnnotation.cs, ios8/SceneKitFSharp/FSSceneKit.sln, ios8/SceneKitFSharp/FSSceneKit/Assets.xcassets/AppIcon.appiconset/Contents.json, ios8/SceneKitFSharp/FSSceneKit/Assets.xcassets/Contents.json, ios8/SceneKitFSharp/FSSceneKit/FSSceneKit.fsproj, ios8/SceneKitFSharp/FSSceneKit/FSSceneKitViewController.fs, ios8/SceneKitFSharp/FSSceneKit/Info.plist, ios8/SceneKitFSharp/FSSceneKit/packages.config
Migrated the project to Unified API
Bug https://bugzilla.xamarin.com/show_bug.cgi?id=46606
=> Fixed bug #46606

GLPaint-GameView/MainWindow.xib, SplitView/SplitView/Screens/DetailView/DetailViewScreen.xib
=> [XISamples]Update xibs

GLCameraRipple/RippleViewController.cs
Without the fix, sample was resulting in a build error
=> Fix a build issue in GLCameraRipple. Please see bug 58676

ios10/SamplePhotoApp/Shared/AssetViewController.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=58336
=> SamplePhotoApp ambiguos call fix

ios11/DragAndDropCustomView/CustomViewDragAndDrop.sln, ios11/DragAndDropCustomView/CustomViewDragAndDrop/AppDelegate.cs, ios11/DragAndDropCustomView/CustomViewDragAndDrop/Main.cs, ios11/DragAndDropCustomView/CustomViewDragAndDrop/ViewController.cs, ios11/DragAndDropCustomView/CustomViewDragAndDrop/ViewController.designer.cs
Add formatting rules to .sln so we don't break formatting again.
=> [ios11] DragAndDrop Custom View - Simplify LoadObjects

Chat/Chat/ChatViewController.cs
see https://stackoverflow.com/questions/46776076/ios11-xcode-9-uibarbuttonitem-issue
=> Fixed UIToolbar issue in iOS 11

.gitignore, Location/Location/Info.plist, Location/Location/Location.csproj, Location/Location/Main.storyboard
- added need properties to the Info.plist for location work
- added ids (accessibility identifier) for future flexibility of UITest
- added *.csproj.user files to ignore via git
=> Fixed "Location" sample

ios11/DragAndDropCollectionView/PhotoAlbum/Info.plist
The "Drag&Drop" is only available for iPad
=> [XI] updated the device family for the "PhotoAlbum" project

RosyWriter/Info.plist
fixed the [bug](https://bugzilla.xamarin.com/show_bug.cgi?id=51615)
=> [XI] added additional privacy descriptions to the "RosyWriter" project

MapDemo/README.md
- Two broken links
- Minor text updates
=> Fixed broken links in MapDemo README

Quotes/PageView.cs
Added additional `Export` attribute for a method.
=> [XI] added additional `Export` attribute ("Quotes" sample)

BindingSample/README.md, BindingSample/src/binding/AssemblyInfo.cs, BindingSample/src/binding/Makefile, BindingSample/src/sample/Xamarin.XMBindingLibrarySample/Xamarin.XMBindingLibrarySample/BindingActions.targets, BindingSample/src/sample/Xamarin.XMBindingLibrarySample/Xamarin.XMBindingLibrarySample/Xamarin.XMBindingLibrarySample.csproj
- fixed linking issues (it didn't work with `arm64`)
- added auto-building of extra library while project is building
=> [XI] fixed BindingSample

StoryboardTable_LocalAuthentication/StoryboardTable/Info.plist
- Added NSFaceIDUsageDescription to enable FaceID on iPhone X
- Updated Bundle Identifier
=> StoryboardTable_LocalAuthentication updates

ios12/XamarinNL/LanguageTaggerTableViewController.cs, ios12/XamarinNL/LanguageTaggerViewController.cs
It's broken after the [PR](https://github.com/xamarin/xamarin-macios/pull/4782).
=> [XI] fixed 'XamarinNL' sample

ios12/SoupChef/SoupChef/Entitlements.plist, ios12/SoupChef/SoupChef/Info.plist, ios12/SoupChef/SoupChefIntents/Entitlements.plist, ios12/SoupChef/SoupChefIntents/Info.plist, ios12/SoupChef/SoupChefIntentsUI/Info.plist
Updated all ids under one formatting. It'll be easier for us to work on the project.
=> Update 'SoupChef' profiles

Hello_iOS/Hello.iOS_MultiScreen/Phoneword_iOS/ViewController.cs, Working_with_images/AppDelegate.cs
Part of docs PR https://github.com/MicrosoftDocs/xamarin-docs/pull/1083
=> typo: Contoller -> Controller

PokerNightVoting/PokerNightVotingViewController.cs
The sample crashes on launch. Ouput you can find [here](https://gist.github.com/mykyta-bondarenko-gl/85f4f3ec4ddd7a686a0830cdd951360c).
=> Fixed 'PokerNightVoting' sample 

BouncingGameEmptyiOS/BouncingGame.iOS/BouncingGame.iOS.csproj, BouncingGameEmptyiOS/BouncingGame.iOS/packages.config, BouncingGameEmptyiOS/BouncingGame/BouncingGame.csproj, BouncingGameEmptyiOS/BouncingGame/packages.config
The sample crashes on launch. Ouput you can find [here](https://gist.github.com/mykyta-bondarenko-gl/0d5690a1f652a71808287a2444e5e5eb).
- fixed launch crash
=> Fixed 'BouncingGame' (empty part)

OpenGL/GLKReflectionMapEffectSkybox/MCViewController.cs
The sample crashes on launch. Ouput you can find [here](https://gist.github.com/mykyta-bondarenko-gl/ebf601f61e16630762ee82fd6061c73a).
- fixed launch crash
=> Fixed 'GLKReflectionMapEffectSkybox' sample

IntroductionToiCloud/iCloudUIDoc/AppDelegate.cs
It crashes on launch if there is no connected account.
- output:
https://gist.github.com/mykyta-bondarenko-gl/ed515d5a57186d13ed99f817a03d250d
=> Fixed 'iCloudUIDoc' sample

ios12/SoupChef/OrderSoupIntentStaticLib/Makefile
Makes this project build with Xcode 10.1.
=> [SoupChef] Build with the iOS SDK available.

ios12/SoupChef/SoupChefIntentsUI/SoupChefIntentsUI.csproj
References: 0665358c2c2d1ea4b9948ad9237686f80a20ba37 and 34b2c368b226d9e2f6b4705b584d5f0300ea63fc.
=> Remove all references to an Entitlements.plist from SoupChefIntentsUI.

README.md
Update instructions for docs.microsoft.com/samples code browser metadata
=> [yaml] update repo readme for new code browser

ios11/WeatherWidget/WeatherWidget.Shared/Weather.cs, ios12/ExceptionalAccessibility/ExceptionalAccessibility/ViewController.cs, ios8/HelloGoodbye/HelloGoodbye/Screens/MatchesViewController.cs
- Fixes https://github.com/xamarin/maccore/issues/1910
- Fixes https://github.com/xamarin/maccore/issues/1877
=> [xcode11] Fix ambiguous calls due to new APIs

ios11/NFCTagReader/NFCTagReader/MessagesTableViewController.cs
- https://github.com/xamarin/ios-samples/issues/385
=> Fix threading issue when NFC scan times out

intro-to-extensions/DayCountExtension/Info.plist
- Fixes https://github.com/xamarin/ios-samples/issues/416
=> Fix intro-to-extensions info.plist

ios11/ARKitPlacingObjects/PlacingObjects/ViewController+ARSceneViewDelegate.cs
Fixes https://github.com/xamarin/ios-samples/issues/446
=> Correct sample which crashes to due binding mistake

nnyeah-samples/README.md
First cut of README - need the locations for packaging and download.
=> [nnyeah] first cut of readme
